name: iqra_islamic_wisdom
description: "Iqra Islamic Wisdom - Islamic knowledge app with Quran, Hadith, and Islamic content."
publish_to: "none"
version: 3.2.0+32

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  provider: ^6.1.2
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.10
  http: ^1.2.2
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.14.1
  connectivity_plus: ^6.0.3
  animated_text_kit: ^4.2.2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/quran/
    - assets/hadith/
    - assets/audio/
    - assets/json/
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: AlQalam
      fonts:
        - asset: assets/fonts/AlQalam.ttf
    - family: NotoNastaliq
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
