name: Flutter Build APK (Islamic Wisdom)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Create temp app and copy source
        run: |
          rm -rf temp_app || true
          flutter create -t app temp_app
          cp -r lib temp_app/
          cp -r assets temp_app/
          cp pubspec.yaml temp_app/
          cd temp_app
          flutter pub get

      - name: Build release APK
        working-directory: temp_app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Islamic_Wisdom_App_Final_v1
          path: temp_app/build/app/outputs/flutter-apk/app-release.apk
