name: Flutter Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.10.0
        
      - name: Fix SDK Version
        run: |
          sed -i 's/sdk:.*>=3.4.0.*/sdk: ">=3.0.0 <4.0.0"/g' pubspec.yaml
          
      - name: Build APK
        run: flutter build apk --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
